# Generated by Django 5.2.6 on 2025-12-15 18:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.FloatField(help_text='Temperatura en °C')),
                ('humedad', models.FloatField(help_text='Humedad relativa (%)')),
                ('ts_sensor', models.DateTimeField(blank=True, null=True)),
                ('ts_server', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoBomba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(help_text='True = encendida, False = apagada')),
                ('ts_sensor', models.DateTimeField(blank=True, null=True)),
                ('ts_server', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='HumedadTierra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(help_text='Porcentaje de humedad en la tierra (0-100)')),
                ('ts_sensor', models.DateTimeField(blank=True, help_text='Timestamp enviado por el ESP32', null=True)),
                ('ts_server', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp cuando se guarda en el servidor')),
            ],
        ),
        migrations.CreateModel(
            name='NivelAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distancia', models.FloatField(help_text='Distancia medida en cm')),
                ('ts_sensor', models.DateTimeField(blank=True, null=True)),
                ('ts_server', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SensorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(max_length=50, unique=True)),
                ('planta', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
            ],
        ),
    ]
